### ISSUE TITLE
Nothing RPROVIDES 'php-cli'

### ISSUE THREAD

**Issue by myke239** [shantanoo-desai/meta-canboat#2]
Hi, 
I'm sure I'm doing something wrong but when I follow the instructions you gave I get this error when I run bitbake. 

ERROR: Nothing RPROVIDES 'php-cli' (but /home/yocto/poky/meta-canboat/recipes-support/canboat/canboat_1.0.0.bb RDEPENDS on or otherwise requires it)

I tried 
INSTALL_IMAGE_append = " canboat php php-cli"

instead of 
INSTALL_IMAGE_append = " canboat"

but no luck.

I'm trying to build this for a raspberry pi 3

Thank You

**Comment by myke239** [comment]
I'm using the latest version of yocto Thud 2.6.1

**Comment by shantanoo-desai** [comment]
@myke239 Hi thanks for testing the layer on Thud. I will look into it, unfortunately the meta layer works and is tested only for `krogoth`. Let me do some research and will get back to you

**Comment by shantanoo-desai** [comment]
@myke239 can you post your `bblayers.conf` here?

**Comment by myke239** [comment]
Thanks for the quick response. I was able to get the image to build by adding the meta-oe layer which contains the dependency php. Here is my .bblayers


```
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/yocto/poky/meta \
  /home/yocto/poky/meta-poky \
  /home/yocto/poky/meta-yocto-bsp \
  /home/yocto/poky/meta-raspberrypi \
  /home/yocto/poky/meta-openembedded/meta-oe \
  /home/yocto/poky/meta-canboat \
 "
```

but now I get this warning:

`WARNING: Layer canboat should set LAYERSERIES_COMPAT_canboat in its conf/layer.conf file to list the core layer names it is compatible with.`

and when I boot the raspberrypi, I am unable to find any of the commands from canboat like candump2analyzer or analyzer

I'm quite familiar with canboat but not so much yocto.


Thanks for the help

**Comment by shantanoo-desai** [comment]
@myke239 I would suggest building the image once again `bitbake -k core-image-minimal` and try adding the following line to the `meta-canboat/conf/layer.conf` file:
`LAYERSERIES_COMPAT_canboat = "bitbakeguilde"`[reference](https://a4z.bitbucket.io/docs/BitBake/guide.html#_layer_compatibility) and see if the warning is removed or not.
see [Reference patch](https://github.com/intel/luv-yocto/commit/f6f2034526009d21036bfc42326f7d883e84b1cb)

**Comment by shantanoo-desai** [comment]
@myke239 any new updates? If you could get rid of the warning and everything works I could close the issue.
Feel free to create a PR if you need to change some files for the layer. or Reopen the issue accordingly
